<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <PropertyGroup>
    <Title>EditIcarusProspect</Title>
    <Product>EditIcarusProspect</Product>
	<ProductName>EditIcarusProspect</ProductName>
    <Description>Modifies an Icarus prospect save file</Description>
    <Company>Crystal</Company>
    <Authors>Crystal Ferrai</Authors>
    <Copyright>Copyright © 2025 Crystal Ferrai</Copyright>
	<Version>1.6.4.0</Version>
	<ProductVersion>$(Version)</ProductVersion>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
	<InformationalVersion>$(Version)</InformationalVersion>
	<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" Version="0.49.1" />
    <ProjectReference Include="..\IcarusSaveLib\IcarusSaveLib\IcarusSaveLib.csproj" />
    <ProjectReference Include="..\IcarusSaveLib\UeSaveGame\UeSaveGame\UeSaveGame.csproj" />
  </ItemGroup>

</Project>
